name: wallet_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.3
  google_sign_in: ^6.1.0
  googleapis: ^11.0.0
  http: ^1.1.0
  intl: ^0.20.3
  dio: ^5.3.0
  logger: ^1.4.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.14.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/currencies.json
